declare const process:{argv:string[];env:Record<string,string|undefined>;cwd():string;execPath:string;exit(code?:number):never};
declare const console:{log(...args:unknown[]):void;error(...args:unknown[]):void;warn(...args:unknown[]):void};
declare class Buffer extends Uint8Array{static from(value:Uint8Array|ArrayBuffer|string):Buffer}
declare module "node:fs/promises"{export function readFile(path:string,encoding?:string):Promise<any>;export function writeFile(path:string,data:any,encoding?:string):Promise<void>;export function readdir(path:string,options?:any):Promise<any[]>;export function stat(path:string):Promise<any>;export function access(path:string):Promise<void>;export function mkdtemp(prefix:string):Promise<string>;export function rm(path:string,options?:any):Promise<void>;export function mkdir(path:string,options?:any):Promise<void>}
declare module "node:path"{export function join(...paths:string[]):string;export function relative(from:string,to:string):string;export function resolve(...paths:string[]):string;export function dirname(path:string):string;export function extname(path:string):string}
declare module "node:url"{export function fileURLToPath(url:string|{toString():string}):string}
declare module "node:os"{export function tmpdir():string}
declare module "node:child_process"{interface Stream{setEncoding(enc:string):void;on(event:string,cb:(arg:any)=>void):void}interface Child{stdout:Stream;stderr:Stream;on(event:string,cb:(arg:any)=>void):void}export function spawn(command:string,args:string[],options:any):Child}
declare module "node:test"{type Fn=()=>void|Promise<void>;export default function test(name:string,fn:Fn):void}
declare module "node:assert/strict"{interface Assert{equal(a:unknown,b:unknown):void;deepEqual(a:unknown,b:unknown):void;ok(v:unknown):void;match(s:string,r:RegExp):void;throws(fn:()=>unknown,expected?:RegExp):void;doesNotThrow(fn:()=>unknown):void}const assert:Assert;export default assert}
declare module "@tonejs/midi"{export class Midi{constructor(data?:Uint8Array);duration:number;header:{tempos:Array<{bpm:number}>};tracks:Array<{notes:Array<{midi:number}>,addNote(v:any):void}>;addTrack():{notes:Array<{midi:number}>,addNote(v:any):void};toArray():Uint8Array}}
